version: "3.8"

services:
  # Servicio de la base de datos MongoDB
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network

  # Servicio de la aplicación NestJS
  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3300:3300"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
